export type ErrorTypes =
  | "JWT"
  | "WRONG_PASSWORD"
  | "VALIDATION_ERROR"
  | "USER_EXISTS"
  | "USER_NOT_EXISTS"
  | "USER_NOT_ACTIVE"
  | "USER_VERIFIED"
  | "USER_NOT_VERIFIED"
  | "INVALID_JWT"
  | "TABLE_NOT_EXISTS"
  | "COLUMN_EXISTS"
  | "COLUMN_NOT_EXIST"
  | "ORDERING_ERROR";
